### ISSUE TITLE
Question regarding the implementation of more functions

### ISSUE THREAD

**Issue by JuanJakobo** [OliverHaag/rust-inkview#2]
Hey,

thanks for the binding. :)
When I want to use a function that is currently not in the lib.rs  (e.g. DrawString), should I implement it into the file or use the plain c_api?

```
pub fn draw_string(x: i32, y: i32, s: &str) {
		let c_str = CString::new(s).expect("CString::new failed");
	unsafe {
		c_api::DrawString(x,y,c_str.as_ptr());
	}
}
```

Regarding the font functions --> do I need to call the close_font function to free the pointer or how does this work regarding C and Rust? Can you tell me how inkview handles this internally?

```
pub fn open_font(name: &str, size: i32, aa: i32) -> *mut c_api::ifont_s {
	let c_str = CString::new(name).expect("CString::new failed");
	unsafe {
		c_api::OpenFont(c_str.as_ptr(),size,aa)
	}
}

pub fn set_font(font: *const c_api::ifont_s, color: Color) {
	unsafe{
		c_api::SetFont(font, color.0)
	}
}

pub fn close_font(f: *mut c_api::ifont_s) {
	unsafe{
		c_api::CloseFont(f);
	} 
}
```

Thanks in advance :+1:

**Comment by OliverHaag** [comment]
Hi Juan,

you're welcome, nice to see it being used. Best add anything missing to the lib.rs, the plan is that no c_api-calls are required for someone using rust-inkview. It's not complete yet since I did just some simpler apps and games for fun with it. You're welcome to leave a merge request with the changes you've done :)

Regarding the font: I think that should be wrapped into a Font-object with a drop calling close_font? You shouldn't return the c_api::ifont_s object because that would spill unsafe c_api objects into the Rust application, you could return the mentioned Font-object instead.

**Comment by JuanJakobo** [comment]
Hi Oliver, 

got it, thank you. :)
